server:
  port: 8081
iotdata.core:
  queue:
    kafka:
      bootstrap.servers: "${ENV_PUB_KAFKA_HOST:192.168.110.244}:${ENV_PUB_KAFKA_PORT:9092}"
      #      bootstrap.servers: "${ENV_PUB_KAFKA_HOST:localhost}:${ENV_PUB_KAFKA_PORT:9092}"
      topic: "${IOTDATA_CORE_QUEUE_KAFKA_TOPIC:ruleEngineToIotdata}"
      group_id: "${IOTDATA_CORE_QUEUE_KAFKA_GROUP_ID:iotdata}"
      enable_auto_commit: "${IOTDATA_CORE_QUEUE_KAFKA_ENABLE_AUTO_COMMIT:false}"
      fetch.max.bytes: "${IOTDATA_CORE_QUEUE_KAFKA_FETCH_MAX_BYTES:52428800}"
      max.poll.records: "${IOTDATA_CORE_QUEUE_KAFKA_MAX_POLL_RECORDS:5000}"

