spring:
    application:
        name: mybatis-plus-test
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: sa
        schema: classpath:db/schema-h2.sql
        data: classpath:db/data-h2.sql
#    sql:
#        init:
#            schema-locations: classpath:db/schema-h2.sql
#            data-locations: classpath:db/data-h2.sql